### ISSUE TITLE
Can I use your tools logo in README

### ISSUE THREAD

**Issue by chenboshuo** [sudnyeshtalekar/sudnyeshtalekar#1]
<img src="https://github.com/sudnyeshtalekar/sudnyeshtalekar/blob/master/Assets/jetbrains_pycharm.svg" alt="pycharm" style="vertical-align:top; margin:4px">
I want to use it in my README, Does it match your LICENSE?

**Comment by sudnyeshtalekar** [comment]
yes you can🙂

**Comment by chenboshuo** [comment]
> yes you can

Thank you.
